project:
  type: website
  preview: 
    port: 4200
  output-dir: docs  

website:
  title: "Boukary O."
  page-navigation: true
  site-url: "https://ouedraogo-boukary.com/"
  
  page-footer:
    left: "Site crée avec [Quarto](https://quarto.org/), par Boukary Ouedraogo. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/deed.fr/)."
    right:
      - icon: github
        href: https://github.com/oboukary/
      - icon: linkedin
        href: https://www.linkedin.com/in/oboukary/
      - icon: envelope
        href: mailto:ouedraogo.boukary89@gmail.com
  
  
  navbar:
    right:
      - href: index.qmd
        text: Home
        
      - text: Posts
        href: posts/index.qmd
        
      - text: Projects
        href: projet.qmd
        
format:
  html:
    theme: [custmer.scss]
    
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.ouedraogo-boukary\.com\/**'
    citations-hover: true
    footnotes-hover: true
    toc: false
    code-link: true


execute:
  freeze: auto
highlight-style: pygments
